# Generated by Django 2.0.5 on 2018-05-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='status_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useritem',
            name='img',
            field=models.TextField(max_length=255),
        ),
    ]
